corpus_path="../gutenberg/cache/epub_copy/"
private_key_path = "../merkle_signing_private_key_new.pem"
public_key_path = "../merkle_signing_public_key.pem"
tree_filename="timestamp/pgmerkle.txt"
date ="June 26, 2026"
time="16:45"
block_lockout=955521
identifier="PGMERKLE" 