corpus_path="../gutenberg/cache/epub_copy/"
private_key_path = "../private_key.pem"
public_key_path = "../public_key.pem"
tree_filename="timestamp/pgmerkle.txt"
date ="June 12, 2026"
time="12:00"
block_lockout=953259
identifier="PGMERKLE" 