# building new merkle tree
corpus_path="/path/to/corpus"
hashes_path="/path/to/hashes/file"
corpus_name="your_corpus_name"
# finalizing new timestamp
locktime=0
identifier="PGMERKLE"
tx_hash="0000000000000000000000000000000000000000000000000000000000000000"
# verifying existing timestamp
provided_tree_path = "path/to/provided/tree"
provided_explain_path = "path/to/provided/explainfile"